version: 0.2
phases:
    install:
        runtime-versions:
            java: openjdk8
    build:
      commands:
        - echo Running tests for surefire junit
        - mvn test -f surefire/pom.xml -fn
        - echo
        - echo Running tests for cucumber with pretty plugin
        - mvn test -Dcucumber.options="--plugin pretty" -f cucumber-pretty/pom.xml -fn
        - echo
        - echo Running tests for cucumber with junit plugin
        - mvn test -Dcucumber.options="--plugin junit:target/cucumber-junit-report.xml" -f cucumber-junit/pom.xml -fn
        - echo
        - echo Running tests for cucumber with json plugin
        - mvn test -Dcucumber.options="--plugin json:target/cucumber-json-report.json" -f cucumber-json/pom.xml -fn
        - echo
        - echo Running tests for testNG
        - mvn test -f testNG/pom.xml -fn
        
reports:
    sampleReportGroup1: #surefire junit reports
      files:
        - '**/*'
      base-directory: 'surefire/target/surefire-reports'
      discard-paths: false
      
    sampleReportGroup2: #Cucumber reports from pretty plugin
      files:
        - '**/*'
      base-directory: 'cucumber-pretty/target/surefire-reports'
      
    sampleReportGroup3: #Cucumber reports from junit plugin
      files:
        - 'cucumber-junit/target/cucumber-junit-report.xml'
        
    sampleReportGroup4: #Cucumber reports from json plugin
      files:
        - 'cucumber-json/target/cucumber-json-report.json'
      file-format: CucumberJson #Type of the report, defaults to JunitXml
      
    sampleReportGroup5: # Junit reports generated by testNG
      files:
        - 'TEST-**/*.xml'
      base-directory: 'testNG/target/surefire-reports'
